/**
 * Card dimensions utility
 */

const CARD_ASPECT_WIDTH = 193;
const CARD_ASPECT_HEIGHT = 281;
const DEFAULT_WIDTH = 130;

export const CARD_DIMENSIONS = {
  WIDTH: DEFAULT_WIDTH,
  HEIGHT: Math.round((DEFAULT_WIDTH * CARD_ASPECT_HEIGHT) / CARD_ASPECT_WIDTH),
  ASPECT_RATIO: CARD_ASPECT_WIDTH / CARD_ASPECT_HEIGHT,
} as const;

const IMAGE_ASPECT_WIDTH = 491;
const IMAGE_ASPECT_HEIGHT = 476;
const DEFAULT_IMAGE_WIDTH = 126;

export const CARD_IMAGE_DIMENSIONS = {
  WIDTH: DEFAULT_IMAGE_WIDTH,
  HEIGHT: Math.round(
    (DEFAULT_IMAGE_WIDTH * IMAGE_ASPECT_HEIGHT) / IMAGE_ASPECT_WIDTH,
  ),
  ASPECT_RATIO: IMAGE_ASPECT_WIDTH / IMAGE_ASPECT_HEIGHT,
} as const;
