module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["**/src/**/__tests__/**/*.test.ts"],
  verbose: true,
  transform: {
    "^.+\\.ts$": ["ts-jest", { tsconfig: "tsconfig.json" }],
  },
  moduleFileExtensions: ["ts", "js", "json"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@battle/(.*)$": "<rootDir>/src/battle/$1",
    "^@battle$": "<rootDir>/src/battle",
    "^@cards/(.*)$": "<rootDir>/src/cards/$1",
    "^@cards$": "<rootDir>/src/cards",
    "^@effects/(.*)$": "<rootDir>/src/effects/$1",
    "^@effects$": "<rootDir>/src/effects",
    "^@ui/(.*)$": "<rootDir>/src/ui/$1",
    "^@ui$": "<rootDir>/src/ui",
    "^@store/(.*)$": "<rootDir>/src/store/$1",
    "^@store$": "<rootDir>/src/store",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@hooks$": "<rootDir>/src/hooks",
    "^@static/(.*)$": "<rootDir>/src/static/$1",
    "^@static$": "<rootDir>/src/static",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@assets$": "<rootDir>/src/assets",
  },
};
