module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  testMatch: [
    "**/src/**/__tests__/**/*.test.ts",
    "**/src/**/__tests__/**/*.test.tsx",
  ],
  setupFilesAfterEnv: ["<rootDir>/src/test-setup.ts"],
  verbose: true,
  transform: {
    "^.+\\.ts$": ["ts-jest", { tsconfig: "tsconfig.json" }],
    "^.+\\.tsx$": ["ts-jest", { tsconfig: "tsconfig.json" }],
  },
  moduleFileExtensions: ["ts", "tsx", "js", "json"],
  moduleNameMapper: {
    "\\.(css|less|scss|sass)$": "<rootDir>/src/__mocks__/styleMock.js",
    "\\.(jpg|jpeg|png|gif|svg|webp)$": "<rootDir>/src/__mocks__/fileMock.js",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@battle/(.*)$": "<rootDir>/src/battle/$1",
    "^@battle$": "<rootDir>/src/battle",
    "^@cards/(.*)$": "<rootDir>/src/cards/$1",
    "^@cards$": "<rootDir>/src/cards",
    "^@effects/(.*)$": "<rootDir>/src/effects/$1",
    "^@effects$": "<rootDir>/src/effects",
    "^@ui/(.*)$": "<rootDir>/src/ui/$1",
    "^@ui$": "<rootDir>/src/ui",
    "^@store/(.*)$": "<rootDir>/src/store/$1",
    "^@store$": "<rootDir>/src/store",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@hooks$": "<rootDir>/src/hooks",
    "^@static/(.*)$": "<rootDir>/src/static/$1",
    "^@static$": "<rootDir>/src/static",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@assets$": "<rootDir>/src/assets",
  },
};
